Description: >
  This template creates an S3 bucket for the EasyERP application.
  The bucket is configured with appropriate security settings and 
  can be used for storing application assets, logs, or other data.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  S3AccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 
        - easyerp-access-logs-${env}-${account}
        - env: !Ref EnvironmentName
          account: !Ref AWS::AccountId
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldAccessLogs
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-EasyERP-AccessLogs-Bucket
        - Key: Environment
          Value: !Ref EnvironmentName

  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: S3AccessLogsBucket
    Properties:
      BucketName: !Sub 
        - easyerp-app-bucket-${env}-${account}
        - env: !Ref EnvironmentName
          account: !Ref AWS::AccountId
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref S3AccessLogsBucket
        LogFilePrefix: access-logs/
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-EasyERP-S3-Bucket
        - Key: Environment
          Value: !Ref EnvironmentName

  S3LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/s3/${EnvironmentName}-easyerp-bucket
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-EasyERP-S3-Logs
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  S3Bucket:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-S3Bucket
  
  S3BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketArn

  S3AccessLogsBucket:
    Description: Name of the S3 access logs bucket
    Value: !Ref S3AccessLogsBucket
    Export:
      Name: !Sub ${AWS::StackName}-S3AccessLogsBucket
  
  S3LogGroup:
    Description: CloudWatch Log Group for S3 bucket logs
    Value: !Ref S3LogGroup
    Export:
      Name: !Sub ${AWS::StackName}-S3LogGroup

